formatter: "markdown document" # this is required

header-from: docs/header.md

recursive:
  enabled: false
  path: modules

content: |-
  {{ .Header }}

  ## Parameters

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 3
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
